title: Web Based Signal Visualisation
url: "https://vincentrodriguez.github.io/signals-visualisation/"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/vincentrodriguez/signals-visualisation"
footer_text: "Visit github page here"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/about"
 - name: "Guides"
   link: "/usage_guide"
 - name: "Concepts"
   link: "/concepts"
