title: Web Based Signal Visualisation
url: "https://vincentrodriguez.github.io/signals-visualisation/"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/vincentrodriguez/signals-visualisation"
footer_text: "Visit github page here"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Guides"
   link: "/signals-visualisation/usage_guide"
 - name: "Tools Used"
   link: "/signals-visualisation/tools"
 - name: "Blog"
   link: "/signals-visualisation/blog"
 - name: "About"
   link: "/signals-visualisation/about"
